### ISSUE TITLE
Error occurs when loading web export: 'SharedArrayBuffer is not defined' 

### ISSUE THREAD

**Issue by RoyVB-Git** [GreatNateDev/Pokemon-Battle-Quest#1]
Tested on multiple browsers, logs below.

[brave.log](https://github.com/user-attachments/files/17445643/brave.log)
[chrome.log](https://github.com/user-attachments/files/17445644/chrome.log)
[firefox.log](https://github.com/user-attachments/files/17445645/firefox.log)

**Comment by GreatNateDev** [comment]
this may be a Redot problem ill see what i can do i can reproduce this

**Comment by GreatNateDev** [comment]
Resolved in new build of Redot it should be up now thanks for the issue!
