### ISSUE TITLE
Press any key to continue is restricted

### ISSUE THREAD

**Issue by RoyVB-Git** [GreatNateDev/Pokemon-Battle-Quest#4]
https://github.com/user-attachments/assets/28d27f69-ce5e-4dd2-a4aa-0947d60b6ee9

"Where is the any key?
![Keyboard-anykey](https://github.com/user-attachments/assets/92916266-d357-4bef-b2c6-7d331077dfdd)

**Comment by GreatNateDev** [comment]
Will be fixed in pr #2
